version: '3.8'

services:

  auth_service:
      build: 
        context: ./backend/auth_service
        dockerfile: Dockerfile
      command: ["./scripts/start.sh"]
      container_name: auth_service
      ports:
        - "8005:8000"
      depends_on:
        auth_db:
          condition: service_healthy
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASS: "34tgw3eg"
        POSTGRES_DB: "auth_service_db"
        POSTGRES_HOST: "auth_db"
        POSTGRES_PORT: "5432"
      networks:
        - app_network

  registration_service:
    build:
      context: ./backend/registration_service
      dockerfile: Dockerfile
    command: ["./scripts/start.sh"]
    container_name: registration_service
    ports:
      - "8006:8000"
    depends_on:
      registration_db:
        condition: service_healthy
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "34tgw3eg"
      POSTGRES_DB: "registration_service_db"
      POSTGRES_HOST: "registration_db"
      POSTGRES_PORT: "5432"
    networks:
      - app_network

  product_service:
    build: 
      context: ./backend/product_service
      dockerfile: Dockerfile
    command: ["./scripts/start.sh"]
    container_name: product_service
    ports:
      - "8007:8000"
    depends_on:
      product_db:
        condition: service_healthy
      auth_service:
        condition: service_started
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "34tgw3eg"
      POSTGRES_DB: "product_service_db"
      POSTGRES_HOST: "product_db"
      POSTGRES_PORT: "5432"
    networks:
      - app_network

  registration_db:
    image: postgres:14
    networks:
      - app_network
    ports:
      - "5437:5432"
    volumes:
      - registration_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "34tgw3eg"
      POSTGRES_DB: "registration_service_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "registration_service_db", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_db:
    image: postgres:14
    networks:
      - app_network
    ports:
      - "5438:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "34tgw3eg"
      POSTGRES_DB: "auth_service_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "auth_service_db", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest_pass"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  product_db:
    image: postgres:14
    networks:
      - app_network
    ports:
      - "5439:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "34tgw3eg"
      POSTGRES_DB: "product_service_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "product_service_db", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  auth_db_data:
  registration_db_data:
  rabbitmq_data:
  product_db_data:
